### ISSUE TITLE
Just wanted to say thanks!

### ISSUE THREAD

**Issue by carsonperrotti** [ComfySoft/ComfyCafe#1]
Not an issue to report. Just wanted to say thank you for making this project public. It has been a great frame of reference for me in so many ways when building my own large scale meteor project. Cheers!

**Comment by scottpleb** [comment]
Reading stuff like that makes my day! Feel free to let me know if there's anything you'd like clarified or documented.

**Comment by carsonperrotti** [comment]
Will do. Cheers!
